package deque;

import java.util.Iterator;

public class ArrayDeque<T> implements Deque<T>, Iterable<T> {
    private T[] items;
    private int size;
    private int nextFirst;
    private int nextLast;

    public ArrayDeque() {
        items = (T[]) new Object[8];
        size = 0;
        nextFirst = 0;
        nextLast = 1;
    }


    private int minusOne(int num) {
        return Math.floorMod(num - 1, items.length);
    }

    private int plusOne(int num) {
        return Math.floorMod(num + 1, items.length);
    }

    private void resize(int capacity) {
        T[] temp = items;
        items = (T[]) new Object[capacity];
        System.arraycopy(temp, plusOne(nextFirst), items, 0, temp.length - plusOne(nextFirst));
        System.arraycopy(temp, 0, items, temp.length - plusOne(nextFirst), nextLast);
    }

    private void expand() {
        resize(items.length * 2);
    }


    private void shrink() {
        resize(items.length / 2);
    }


    @Override
    public void addFirst(T item) {
        if (size == items.length) {
            expand();
        } else if (items.length > 8 && size < items.length / 4) {
            shrink();
        }

        items[nextFirst] = item;
        nextFirst = minusOne(nextFirst);
        size++;
    }

    @Override
    public void addLast(T item) {
        if (size == items.length) {
            expand();
        } else if (items.length > 8 && size < items.length / 4) {
            shrink();
        }

        items[nextLast] = item;
        nextLast = plusOne(nextLast);
        size++;
    }

    @Override
    public int size() {
        return size;
    }

    @Override
    public void printDeque() {
        for (int i = plusOne(nextFirst); i != minusOne(nextLast); i = plusOne(i)) {
            System.out.print(items[1] + " ");
        }
    }

    @Override
    public T removeFirst() {
        if (isEmpty()) {
            return null;
        }
        if (size == items.length) {
            expand();
        } else if (items.length > 8 && size < items.length / 4) {
            shrink();
        }

        T ret = items[plusOne(nextFirst)];
        items[plusOne(nextFirst)] = null;
        nextFirst = plusOne(nextFirst);
        size--;
        return ret;
    }

    @Override
    public T removeLast() {
        if (isEmpty()) {
            return null;
        }
        if (size == items.length) {
            expand();
        } else if (items.length > 8 && size < items.length / 4) {
            shrink();
        }

        T ret = items[minusOne(nextLast)];
        items[minusOne(nextLast)] = null;
        nextLast = minusOne(nextLast);
        size--;
        return ret;
    }

    @Override
    public T get(int index) {
        return items[Math.floorMod(index + nextFirst + 1, items.length)];
    }

    @Override
    public Iterator<T> iterator() {
        return new ArrayDequeIterator();
    }

    private class ArrayDequeIterator implements Iterator<T> {
        int wizardPos;

        ArrayDequeIterator() {
            wizardPos = 0;
        }

        @Override
        public boolean hasNext() {
            return wizardPos < size;
        }

        @Override
        public T next() {
            T returnItem = items[wizardPos];
            wizardPos++;
            return returnItem;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj == null || obj.getClass() != this.getClass()) {
            return false;
        }

        ArrayDeque<T> o = (ArrayDeque<T>) obj;
        if (size != o.size()) {
            return false;
        }
        for (int i = 0; i < size; i++) {
            if (!get(i).equals(o.get(i))) {
                return false;
            }
        }
        return true;
    }

//    auto generated by intellij.
//    @Override
//    public boolean equals(Object o) {
//        if (this == o) return true;
//        if (o == null || getClass() != o.getClass()) return false;
//        ArrayDeque<?> that = (ArrayDeque<?>) o;
//        return size == that.size && nextFirst
//        == that.nextFirst && nextLast
//        == that.nextLast && Arrays.equals(items, that.items);
//    }
//    @Override
//    public int hashCode() {
//        int result = Objects.hash(size, nextFirst, nextLast);
//        result = 31 * result + Arrays.hashCode(items);
//        return result;
//    }
}
